apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
        - name: food-app
          image: food-app:latest
          env:
            - name: PG_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_CONN_STR
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: food-app
spec:
  selector:
    app: food-app
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
