apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: mahesh
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: food-app
  PG_CONN_STR: postgres://mahesh:secret@postgres:5432/food-app?sslmode=disable
